"""remove player_state

Revision ID: 1f2de0cae2f3
Revises: 9765bea94280
Create Date: 2016-06-17 15:34:07.269229

"""

# revision identifiers, used by Alembic.
revision = '1f2de0cae2f3'
down_revision = '9765bea94280'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_state')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('playing', sa.BOOLEAN(), nullable=True),
    sa.Column('volume', sa.FLOAT(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.Column('block_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
